default:
    image: alpine

build front:
  stage: build
  image: node:16
  variables:
    VITE_API_URL: $STAGE_PROTOCOL://$STAGE_SERVER/api/mis/
  only:
    - dev
  script:
    - npm install --progress=false
    - npm run build:dev
  artifacts:
    expire_in: 1 week
    paths:
       - dist

stage_deploy:
    stage: deploy
    only:
      - dev
    script:
      - apk add --no-cache openssh rsync
      - mkdir -p ~/.ssh
      - echo "$STAGE_KEY" >> ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - rsync -rav --delete dist/ $STAGE_USER@$STAGE_SERVER:/var/www/mis

build front prod:
  stage: build
  image: node:16
  variables:
    VITE_API_URL: $PROD_PROTOCOL://$PROD_SERVER/api/mis/
  only:
    - main
  script:
    - npm install --progress=false
    - npm run build:prod
  artifacts:
    expire_in: 1 week
    paths:
      - dist

prod_deploy:
  stage: deploy
  only:
    - main
  script:
    - apk add --no-cache openssh rsync
    - mkdir -p ~/.ssh
    - echo "$PROD_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ $PROD_USER@$PROD_SERVER:/var/www/mis
